/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authAnonymousRouteImport } from './routes/(auth)/_anonymous'
import { Route as appAuthenticatedRouteImport } from './routes/(app)/_authenticated'
import { Route as authAnonymousSignupRouteImport } from './routes/(auth)/_anonymous/signup'
import { Route as authAnonymousLoginRouteImport } from './routes/(auth)/_anonymous/login'
import { Route as appAuthenticatedDashboardRouteImport } from './routes/(app)/_authenticated/dashboard'
import { Route as apiApiAuthSplatRouteImport } from './routes/(api)/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authAnonymousRoute = authAnonymousRouteImport.update({
  id: '/(auth)/_anonymous',
  getParentRoute: () => rootRouteImport,
} as any)
const appAuthenticatedRoute = appAuthenticatedRouteImport.update({
  id: '/(app)/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authAnonymousSignupRoute = authAnonymousSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authAnonymousRoute,
} as any)
const authAnonymousLoginRoute = authAnonymousLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authAnonymousRoute,
} as any)
const appAuthenticatedDashboardRoute =
  appAuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => appAuthenticatedRoute,
  } as any)
const apiApiAuthSplatRoute = apiApiAuthSplatRouteImport.update({
  id: '/(api)/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof appAuthenticatedDashboardRoute
  '/login': typeof authAnonymousLoginRoute
  '/signup': typeof authAnonymousSignupRoute
  '/api/auth/$': typeof apiApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof appAuthenticatedDashboardRoute
  '/login': typeof authAnonymousLoginRoute
  '/signup': typeof authAnonymousSignupRoute
  '/api/auth/$': typeof apiApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)/_authenticated': typeof appAuthenticatedRouteWithChildren
  '/(auth)/_anonymous': typeof authAnonymousRouteWithChildren
  '/(app)/_authenticated/dashboard': typeof appAuthenticatedDashboardRoute
  '/(auth)/_anonymous/login': typeof authAnonymousLoginRoute
  '/(auth)/_anonymous/signup': typeof authAnonymousSignupRoute
  '/(api)/api/auth/$': typeof apiApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/login' | '/signup' | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/login' | '/signup' | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/(app)/_authenticated'
    | '/(auth)/_anonymous'
    | '/(app)/_authenticated/dashboard'
    | '/(auth)/_anonymous/login'
    | '/(auth)/_anonymous/signup'
    | '/(api)/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appAuthenticatedRoute: typeof appAuthenticatedRouteWithChildren
  authAnonymousRoute: typeof authAnonymousRouteWithChildren
  apiApiAuthSplatRoute: typeof apiApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_anonymous': {
      id: '/(auth)/_anonymous'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAnonymousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_authenticated': {
      id: '/(app)/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_anonymous/signup': {
      id: '/(auth)/_anonymous/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authAnonymousSignupRouteImport
      parentRoute: typeof authAnonymousRoute
    }
    '/(auth)/_anonymous/login': {
      id: '/(auth)/_anonymous/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authAnonymousLoginRouteImport
      parentRoute: typeof authAnonymousRoute
    }
    '/(app)/_authenticated/dashboard': {
      id: '/(app)/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appAuthenticatedDashboardRouteImport
      parentRoute: typeof appAuthenticatedRoute
    }
    '/(api)/api/auth/$': {
      id: '/(api)/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof apiApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface appAuthenticatedRouteChildren {
  appAuthenticatedDashboardRoute: typeof appAuthenticatedDashboardRoute
}

const appAuthenticatedRouteChildren: appAuthenticatedRouteChildren = {
  appAuthenticatedDashboardRoute: appAuthenticatedDashboardRoute,
}

const appAuthenticatedRouteWithChildren =
  appAuthenticatedRoute._addFileChildren(appAuthenticatedRouteChildren)

interface authAnonymousRouteChildren {
  authAnonymousLoginRoute: typeof authAnonymousLoginRoute
  authAnonymousSignupRoute: typeof authAnonymousSignupRoute
}

const authAnonymousRouteChildren: authAnonymousRouteChildren = {
  authAnonymousLoginRoute: authAnonymousLoginRoute,
  authAnonymousSignupRoute: authAnonymousSignupRoute,
}

const authAnonymousRouteWithChildren = authAnonymousRoute._addFileChildren(
  authAnonymousRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appAuthenticatedRoute: appAuthenticatedRouteWithChildren,
  authAnonymousRoute: authAnonymousRouteWithChildren,
  apiApiAuthSplatRoute: apiApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
